event/urls.py
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = 'event'

urlpatterns = [
    path('', event, name='event'),
    path('sched_add/', sched_add, name='sched_add'),
    path('sched_edit/<int:pk>', sched_edit, name='sched_edit'),
    path('sched_delete/<int:pk>', sched_delete, name='sched_delete'),
]

sarangkarir/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('article/', include('article.urls',namespace='article')),
    path('contact/', include('contact.urls', namespace = 'contact')),
    path('event/', include('event.urls', namespace ='event')),

]

event/models.py
from django.db import models
import datetime

class event(models.Model):
    dates = models.DateField()
    time = models.TimeField()
    eventname = models.CharField(max_length=50)
    eventdesc = models.CharField(max_length=500)
    location = models.CharField(max_length=50)
    rsvp = models.CharField(max_length=30)

event/forms.py
from django import forms
from .models import event
from django.forms import ModelForm

class eventForm(ModelForm):
    class Meta:
        model= event
        fields = ['dates', 'time', 'eventname', 'location', 'rsvp', 'eventdesc']
        labels = {
            'dates' : 'Date', 'time' : 'Time', 'eventname' : 'Event Name', 'location' : 'Location', 'rsvp' : 'RSVP', 'eventdesc' : 'Description'
        }
        widgets = {
            'dates' : forms.DateInput(attrs={'class': 'form-control',
                                        'type' : 'date'}),
            'time' : forms.TimeInput(attrs={'class': 'form-control',
                                        'type' : 'time'}),
            'eventname' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'Name of the event'}),
            'location' : forms.TextInput(attrs={'class' : 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'Location'}),
            'rsvp' : forms.TextInput(attrs={'class': 'form-control',
                                              'type' : 'text'}),
            'eventdesc' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'Description of the event'}),
        }

event/views.py
from django.shortcuts import render
from .forms import eventForm
from .models import event as jobfair
from django.shortcuts import redirect
import datetime

def sched_add(request):
    if request.method == 'POST':
        form = eventForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('event:event')
    else:
        form = eventForm()

    content = {'title' : 'Form event',
                'form' : form}

    return render(request, 'sched_add.html', content)

def event(request):
    data = jobfair.objects.all()
    context = {
        'data' : data,
    }
    return render(request, 'event.html', context)

def sched_edit(request, pk):
    post = jobfair.objects.get(pk=pk)
    if request.method == "POST":
        form = eventForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('event:event')
    else:
        form = eventForm(instance=post)

    content = {'title' : 'Form event',
                'form' : form,
                'obj' : post}
    return render(request, 'sched_edit.html', content)

def sched_delete(request, pk):
    jobfair.objects.filter(pk=pk).delete()
    data = jobfair.objects.all()
    return redirect('event:event')

event/templates/event.html
<!DOCTYPE html>
{% load static %}
<head>
    <link rel="stylesheet" href="">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
     <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
     <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
     <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<style>
    body{
      animation: fade-in 2s;
    }

    .navbar a{
        font-family: 'Roboto', sans-serif;
        font-size: 20px;
    }

    .navbar-dark .navbar-brand {
        margin-right: 35px;
    }

    div {
        word-wrap: break-word;
    }

    .navbar-nav > li{
        margin-left:30px;
        margin-right:30px;
    }

    .custom-toggler .navbar-toggler-icon {
        align-content: center;
        background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(200,200,200)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E");

      }

    .custom-toggler.navbar-toggler {
        border-color: rgb(200,200,200);
        border-width: 1.5px;;
    }

    @keyframes fade-in{
      from {opacity: 0;}
      to {opacity: 1;}
    }
    .event{
    font-family: Roboto;
    font-style: normal;
    font-weight: normal;
    font-size: 48px;
    text-align: center;
    padding-top: 70px;
    display: block;
    color: #000000;

    text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }

    html{
        scroll-behavior: smooth;
        overflow-x: hidden;
    }

    body{
        animation: fade-in 2s;
    }

    .text{
        font-family: 'Roboto', sans-serif;
        font-style: normal;
        font-weight: normal;
        letter-spacing: 2px;
        font-size: 15px;
        line-height: 30px;
        color: #000000;
    }

    ol {
        list-style: none;
        display: block;
        padding-top: 20px;
    }
    ol li {
        width: 50px;
        height: 50px;
        background: #e59500;
        margin: 35px 0;
        border-radius: 3px;
        position: relative;
        cursor: pointer;
        box-shadow: 0 0 10px rgba(0,0,0,0.3);
    }
    ol li .fa {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%,-50%);
        font-size: 20px;
    }
    @media (min-width: 768px) {
    .carousel-multi-item-2 .col-md-3 {
    float: left;
    width: 50%;
    max-width: 100%; } }

    .carousel-multi-item-2 .card img {
    border-radius: 2px; 
    width:220px;
    height: 140px;}

</style>
<body>
    {% block navbar %}
    {% include 'components/navbar.html' %}
    {% endblock navbar %}

    <h1 class="event" style="padding-top: 100px">UPCOMING EVENTS</h1>
    {% csrf_token %}
    <div id="sched" >
        <div class="container-fluid">
            <div class="row" style="padding-top: 50px">
                <div class="col">
                    <a href="{% url 'event:sched_add' %}"><button data-toggle="modal" data-target="#con-close-modal" class="btn btn-icon btn-primary" style="float: right !important; margin-right: 10px; margin-bottom: 5px;">
                        <i class="fa fa-plus-circle"></i>
                    </button></a>
                    <table class="table m-0">
                        <thead>
                            <tr>
                                <th>Event Name</th>
                                <th>Event Description</th>
                                <th>Day</th>
                                <th>Date</th>
                                <th>Time</th>
                                <th>Location</th>
                                <th>RSVP</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for obj in data %}
                            <tr>
                                <td>{{ obj.eventname }}</td>
                                <td>{{ obj.eventdesc }}</td>
                                <td>{{ obj.dates|date:"l" }}</td>
                                <td>{{ obj.dates }}</td>
                                <td>{{ obj.time }}</td>
                                <td>{{ obj.location }}</td>
                                <td>{{ obj.rsvp }}</td>
                                <td><a href="{% url 'event:sched_edit'  pk=obj.pk %}"><button data-toggle="modal" data-target="#con-close-modal" class="btn btn-icon btn-info"><i class="fa fa-keyboard"></i></button></a></td>
                                <td><a href="{% url 'event:sched_delete' pk=obj.pk %}"><button class="btn btn-icon btn-danger"><i class="fa fa-trash"></i></button></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col">
                    <div id="multi-item-example" class="carousel slide carousel-multi-item carousel-multi-item-2" data-ride="carousel">

                        <h4 style="padding-bottom: 20px">Here are some pictures of previous events...</h4>
                        <!--Slides-->
                        <div class="carousel-inner" role="listbox">
                      
                          <!--First slide-->
                          <div class="carousel-item active">
                      
                            <div class="col-md-3 mb-3">
                              <div class="card">
                                <img class="img-fluid" src="{% static 'eventimages/jobfair1.jpg' %}"
                                  alt="Card image cap">
                                  <p style="text-align: center">JOBin 2018</p>
                              </div>
                            </div>
                      
                            <div class="col-md-3 mb-3">
                              <div class="card">
                                <img class="img-fluid" src="{% static 'eventimages/jobfair2.jpg' %}"
                                  alt="Card image cap">
                                  <p style="text-align: center">Young Entrepreneurs 2018</p>
                              </div>
                            </div>
                          </div>
                          <!--/.First slide-->
                      
                          <!--Second slide-->
                          <div class="carousel-item">
                      
                            <div class="col-md-3 mb-3">
                              <div class="card">
                                <img class="img-fluid" src="{% static 'eventimages/jobfair3.jpg' %}"
                                  alt="Card image cap">
                                  <p style="text-align: center">STARSHIP 2019</p>
                              </div>
                            </div>
                      
                            <div class="col-md-3 mb-3">
                              <div class="card">
                                <img class="img-fluid" src="{% static 'eventimages/jobfair4.jpg' %}"
                                  alt="Card image cap">
                                  <p style="text-align: center">FindCorp 2019</p>
                              </div>
                            </div>
                          </div>
                          <!--/.Second slide-->
                      
                          <!--Third slide-->
                          <div class="carousel-item">
                      
                            <div class="col-md-3 mb-3">
                              <div class="card">
                                <img class="img-fluid" src="{% static 'eventimages/jobfair5.jpg' %}"
                                  alt="Card image cap">
                                  <p style="text-align: center">National JobFair 2018</p>
                              </div>
                            </div>
                      
                            <div class="col-md-3 mb-3">
                              <div class="card">
                                <img class="img-fluid" src="{% static 'eventimages/jobfair6.jpg' %}"
                                  alt="Card image cap">
                                  <p style="text-align: center">Beauty JobFair 2017</p>
                              </div>
                            </div>
                          </div>
                          <!--/.Third slide-->
                        </div>
                        <!--/.Slides-->
                      
                      </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

event/templates/sched_add.html
<!DOCTYPE html>
{% load static %}
<head>
    <link rel="stylesheet" href="">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
     <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
     <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
     <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<style>
    body{
      animation: fade-in 2s;
    
    }

    .navbar a{
        font-family: 'Roboto', sans-serif;
        font-size: 20px;
    }

    .navbar-dark .navbar-brand {
        margin-right: 35px;
    }

    div {
        word-wrap: break-word;
    }

    .navbar-nav > li{
        margin-left:30px;
        margin-right:30px;
    }

    .custom-toggler .navbar-toggler-icon {
        align-content: center;
        background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(200,200,200)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E");

      }

    .custom-toggler.navbar-toggler {
        border-color: rgb(200,200,200);
        border-width: 1.5px;;
    }

    @keyframes fade-in{
      from {opacity: 0;}
      to {opacity: 1;}
    }
    .event{
    font-family: Roboto;
    font-style: normal;
    font-weight: normal;
    font-size: 48px;
    text-align: center;
    padding-top: 70px;
    display: block;
    color: #000000;

    text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }

    html{
        scroll-behavior: smooth;
        overflow-x: hidden;
    }

    body{
        animation: fade-in 2s;
    }

    .text{
        font-family: 'Roboto', sans-serif;
        font-style: normal;
        font-weight: normal;
        letter-spacing: 2px;
        font-size: 15px;
        line-height: 30px;
        color: #000000;
    }

    ol {
        list-style: none;
        display: block;
        padding-top: 20px;
    }
    ol li {
        width: 50px;
        height: 50px;
        background: #e59500;
        margin: 35px 0;
        border-radius: 3px;
        position: relative;
        cursor: pointer;
        box-shadow: 0 0 10px rgba(0,0,0,0.3);
    }
    ol li .fa {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%,-50%);
        font-size: 20px;
    }
</style>
<body>
    {% block navbar %}
    {% include 'components/navbar.html' %}
    {% endblock navbar %}

    <h1 class="event"style="padding-top: 100px">ADD AN EVENT</h1>
    <div id = "sched">
        <div class="container-fluid">
            <h1>Schedule</h1>
            <hr>
            <form class="left" style="width: 50%; margin: 0 auto" method="POST" action="{% url 'event:sched_add' %}" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label for="eventname"><strong>{{ form.eventname.label_tag }}</strong></label>
                    {{ form.eventname }}
                </div>
                <div class="form-group">
                        <label for="eventdesc"><strong>{{ form.eventdesc.label_tag }}</strong></label>
                        {{ form.eventdesc }}
                    </div>
                <div class="form-group">
                    <label for="dates"><strong>{{ form.dates.label_tag }}</strong></label>
                    {{ form.dates }}
                </div>
                <div class="form-group">
                    <label for="time"><strong>{{ form.time.label_tag }}</strong></label>
                    {{ form.time }}
                </div>
                <div class="form-group">
                    <label for="location"><strong>{{ form.location.label_tag }}</strong></label>
                    {{ form.location }}
                </div>
                <div class="form-group">
                    <label for="rsvp"><strong>{{ form.rsvp.label_tag }}</strong></label>
                    {{ form.rsvp }}
                </div>
                <br>
                <button type="submit" class="btn btn-primary waves-effect waves-light" value="Save"><h4>Add</h4></button>
            </form>
            <hr>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

event/templates/sched_edit.html
<!DOCTYPE html>
{% load static %}
<head>
    <link rel="stylesheet" href="">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
     <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
     <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
     <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<style>
    body{
      animation: fade-in 2s;
    
    }

    .navbar a{
        font-family: 'Roboto', sans-serif;
        font-size: 20px;
    }

    .navbar-dark .navbar-brand {
        margin-right: 35px;
    }

    div {
        word-wrap: break-word;
    }

    .navbar-nav > li{
        margin-left:30px;
        margin-right:30px;
    }

    .custom-toggler .navbar-toggler-icon {
        align-content: center;
        background-image: url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(200,200,200)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E");

      }

    .custom-toggler.navbar-toggler {
        border-color: rgb(200,200,200);
        border-width: 1.5px;;
    }

    @keyframes fade-in{
      from {opacity: 0;}
      to {opacity: 1;}
    }
    .event{
    font-family: Roboto;
    font-style: normal;
    font-weight: normal;
    font-size: 48px;
    text-align: center;
    padding-top: 70px;
    display: block;
    color: #000000;

    text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }

    html{
        scroll-behavior: smooth;
        overflow-x: hidden;
    }

    body{
        animation: fade-in 2s;
    }

    .text{
        font-family: 'Roboto', sans-serif;
        font-style: normal;
        font-weight: normal;
        letter-spacing: 2px;
        font-size: 15px;
        line-height: 30px;
        color: #000000;
    }

    ol {
        list-style: none;
        display: block;
        padding-top: 20px;
    }
    ol li {
        width: 50px;
        height: 50px;
        background: #e59500;
        margin: 35px 0;
        border-radius: 3px;
        position: relative;
        cursor: pointer;
        box-shadow: 0 0 10px rgba(0,0,0,0.3);
    }
    ol li .fa {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%,-50%);
        font-size: 20px;
    }
</style>
<body>
    {% block navbar %}
    {% include 'components/navbar.html' %}
    {% endblock navbar %}

    <h1 class="event"style="padding-top: 100px">EDIT AN EVENT</h1>
    <div id = "sched">
        <div class="container-fluid">
            <hr>
            <form class="left" style="width: 50%; margin: 0 auto" method="POST" action="{% url 'event:sched_edit' pk=obj.pk %}" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label for="eventname"><strong>{{ form.eventname.label_tag }}</strong></label>
                    {{ form.eventname }}
                </div>
                <div class="form-group">
                        <label for="eventdesc"><strong>{{ form.eventdesc.label_tag }}</strong></label>
                        {{ form.eventdesc }}
                    </div>
                <div class="form-group">
                    <label for="dates"><strong>{{ form.dates.label_tag }}</strong></label>
                    {{ form.dates }}
                </div>
                <div class="form-group">
                    <label for="time"><strong>{{ form.time.label_tag }}</strong></label>
                    {{ form.time }}
                </div>
                <div class="form-group">
                    <label for="location"><strong>{{ form.location.label_tag }}</strong></label>
                    {{ form.location }}
                </div>
                <div class="form-group">
                    <label for="rsvp"><strong>{{ form.rsvp.label_tag }}</strong></label>
                    {{ form.rsvp }}
                </div>
                <br>
                <button type="submit" class="btn btn-primary waves-effect waves-light" value="Save"><h4>Save</h4></button>
            </form>
            <hr>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>