article/urls.py
from django.conf.urls import url
from django.urls import path
from .views import articles, articles_create

app_name = 'articles'

urlpatterns = [
    
    path('articles/', articles, name='articles'),
    path('articles_create/', articles_create, name='article2')
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('',views.contact, name='contact'),

]

event/urls.py
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = 'event'

urlpatterns = [
    path('', event, name='event'),
    path('sched_add/', sched_add, name='sched_add'),
    path('sched_edit/<int:pk>', sched_edit, name='sched_edit'),
    path('sched_delete/<int:pk>', sched_delete, name='sched_delete'),
]

homepage/urls.py
from django.urls import path
from .views import index, preference

app_name = 'homepage'

urlpatterns = [
    path('', index, name='index'),
    path('preference/', preference, name='preference'),
]

sarangkarir/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('article/', include('article.urls',namespace='article')),
    path('contact/', include('contact.urls', namespace = 'contact')),
    path('event/', include('event.urls', namespace ='event')),

]

templates/components/head.html
{% load static %}
<meta charset="UTF-8">
<title>SarangKarir</title>
<link href="https://fonts.googleapis.com/css?family=Manjari|Montserrat:300,400,500,600|Poppins:400,600|Roboto:100,300,400,500,700,900|Monoton&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="icon" type="image/ico" href="{% static 'images/sarangkarir Logo.png' %}">

templates/components/navbar.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'homepage:index' %}">
        <img src="{% static 'images/sarangkarir Logo.png' %}" alt="scratch" style="width:40px; height: 55px;">
    </a>
    <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage:index' %}">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'homepage:preference' %}">Find</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'article:article2' %}">Article</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'event:event' %}">Jobfair</a>
            </li>
        </ul>
    </div>
</nav>